### ISSUE TITLE
Tree-based job dependencies

### ISSUE THREAD

**Issue by notmeta** [notmeta/Gope#8]
![.](https://cdn.discordapp.com/attachments/519831052475170817/676076315132297248/Gope_tree-based_jobs.png)

**Comment by notmeta** [comment]
Initial brainstorm of matching TOML config:
```toml
[[job]]
entry = true
name = "check space"
command = "df"
timeout = 20

on.timeout.code = 3 # not in diagram

on.3.name = "clear disk space"
on.3.retry.tries = 5
on.3.retry.then = "disk space email"

on.0.name = "check connection"

[[job]]
name = "clear disk space"
command = "rm -r /etc/somedir/logs"
timeout = 20

[[job]]
name = "disk space email"
email.recipient = "devops@e-corp.com"
email.subject = "Error in job"
email.body = "Failed to clean up enough disk space"


[[job]]
name = "check connection"
command = "ping 8.8.8.8"
timeout = 10

on.0.name = "dump mysql"
on.3.name = "no internet email"

[[job]]
name = "no internet email"
email.recipient = "devops@e-corp.com"
email.subject = "No internet connection!"
email.body = "Fix me"


[[job]]
name = "dump mysql"
command = "mysqldump -u root test > test.sql"
timeout = 180

# TODO on.timeout

on.unknown.name = "mysql dump email"
on.0.name = "upload dump"
on.0.retry.tries = 5
on.0.retry.then = "upload fail email"

[[job]]
name = "mysql dump email"
email.recipient = "devops@e-corp.com"
email.subject = "Faild to dump mysql db"
email.body = """
mysqldump failed with code ${{code}}

${{stdout}}

${{stderr}}
"""


[[job]]
name = "upload dump"
command = "aws s3 put test.sql"
timeout = 180

[[job]]
name = "upload fail email"
email.recipient = "devops@e-corp.com"
email.subject = "Failed to upload db dump"
email.body = """
failed to upload db dump to s3

${{sterr}}
"""
```

Further ideas
- `on.default.` in entry job to specify default behaviour for jobs that don't explicitly specify unknown codes

Key differences from current format
- job names are set by a `name` attribute
  - `[[job]]`
- chaining, such as `on.3.retry.tries`
- `entry` value in job
- calling other jobs by name on certain events, instead of just giving command strings
- support for default behaviour

Todo
- come up with more trees and map to config
- think about webhook vars and transfer of variables in general to other jobs (such as previous `stdout`, `stderr`, etc)
